id: A27BA5085
title: Dhāraṇī of Goddess Parṇaśavarī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:34.729619
  last_modified_at: 2022-03-01 05:01:34.729623
